# Generated by Django 2.1.1 on 2018-09-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180916_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readnum',
            old_name='readed_num',
            new_name='readnum',
        ),
    ]
